---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-json
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
            language_version: python3 # Should be a command that runs python3.6+

    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
            args: [--count, --show-source, --statistics, --max-line-length=90]
            additional_dependencies:
                - flake8-bugbear==22.7.1
            exclude: widget_bandsplot/__init__.py

    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile, black, --filter-files]

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.28.0
      hooks:
          - id: check-github-workflows
          - id: check-jsonschema
            files: ^examples/data/.*\_dos\.json$
            args: [--schemafile, widget_bandsplot/schemas/pdos.json]
