---
# Run basic CI tests.

name: continuous-integration

on: [push, pull_request]

jobs:
    pre-commit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install pre-commit==3.0.4

            - name: Run pre-commit
              run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    voila-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 15.x

            - name: Cache Python dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.cache/pip
                  key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                  restore-keys: pip-${{ matrix.python-version }}-tests

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  pip install --upgrade pip setuptools wheel
                  pip install -e .[tests]
                  pip install -U voila==0.4
                  pip install -U nbconvert==7.2.5

            - name: Run the voila server
              run: |
                  voila --enable_nbextensions=True examples/ --port 8383 --no-browser &

            - uses: nanasess/setup-chromedriver@master
            - run: |
                  export DISPLAY=:99
                  chromedriver --url-base=/wd/hub &
                  sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
                  python $GITHUB_WORKSPACE/tests/voila-test.py

            - uses: actions/upload-artifact@v2
              with:
                  name: screenshot
                  path: ./*.png

    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        steps:
            - uses: actions/checkout@v2

            - name: Cache Python dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.cache/pip
                  key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                  restore-keys: pip-${{ matrix.python-version }}-tests

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip setuptools wheel
                  pip install -e .[tests]

            - name: Run pytest
              run: pytest -sv tests
