# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    deploy:
    
      runs-on: ubuntu-latest
    
      steps:
        - uses: actions/checkout@v2
        # Make sure the @v0.5.1 matches the current version of the
        # action 
        - uses: webfactory/ssh-agent@v0.5.1
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: deploy on dokku
          run: |
            git push dokku@matcloud.xyz:osscar-widget-bandsplot develop:master
            
            
        
      
